# Generated by Django 2.0 on 2017-12-03 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('telephone_number', models.CharField(max_length=12)),
                ('room', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campus_master.User'),
        ),
    ]
