# Generated by Django 2.0 on 2017-12-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('room', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
