# Generated by Django 2.0 on 2017-12-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_master', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_master.User'),
        ),
    ]
