# Generated by Django 2.0 on 2018-01-29 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_master', '0003_auto_20171212_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
